<main class="section-form-register">
    <form action="/addRegister" method="post" class="form-register">
        <input type="text" name="name" placeholder="nome" required>
        <input type="text" name="email" placeholder="email" required>
        <input type="password" name="password" placeholder="senha" required>
        <input type="submit" value="entrar" class="btn-form">
    </form>
</main>