<?php 
    echo '<pre>';
    print_r($this->view->cartItems);
    echo '</pre>';
?>
<main class="cart-container">
    <table class="table-cart">
        <thead>
            <th>produto</th>
            <th>preco</th>
            <th>quantidade</th>
        </thead>
        <tbody>
             
        </tbody>
    </table>
    <div>
        <a href="#" class="btn-table-cart">Finalizar compra</a>
    </div>
</main>