<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>

<body>
    <h2>index</h2> 

    <div class="produto">
        <h2>nome produto</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem est exercitationem, 
        recusandae reprehenderit dolore dolores eum ad laudantium ullam molestiae, 
        omnis aspernatur tempora et cum asperiores corporis. Voluptas, ipsam quam!</p>
        <a href="/add_item?id=5&name=tenis&price=50.00&id_user=62">adicionar ao carrinho</a>
    </div>  
</body>
</html>