<main>
    <section class="banner">
        <div class="image-banner">
            <img src="img/BANNER-3.jpg" alt="balcão">
        </div>
        <div class="text-banner">
            <p>Desconto de <br> <span>50%</span>  <br> em Toda linha<br> de *cozinha</p>
        </div>
    </section>

    <h1 class="title-section">Melhores ofertas</h1>

    <section class="product-offer">
        <div><img src="img/BANNER-3.jpg" alt=""></div>
        <div><img src="img/BANNER-3.jpg" alt=""></div>
        <div><img src="img/BANNER-3.jpg" alt=""></div>
        <div><img src="img/BANNER-3.jpg" alt=""></div>
    </section>

    <h1 class="title-section">Mais vendidos</h1>

    <section class="products">
        <a class="card" href="#">
            <img src="img/BANNER-3.jpg" alt="">
            <h2>nome produto</h2>
            <h3>20.00</h3>
        </a>

        <a class="card" href="#">
            <img src="img/BANNER-3.jpg" alt="">
            <h2>nome produto</h2>
            <h3>20.00</h3>
        </a>

        <a class="card" href="#">
            <img src="img/BANNER-3.jpg" alt="">
            <h2>nome produto</h2>
            <h3>20.00</h3>
        </a>

        <a class="card" href="#">
            <img src="img/BANNER-3.jpg" alt="">
            <h2>nome produto</h2>
            <h3>20.00</h3>
        </a>
    </section>
</main>