<main>
    <section class="product">
        <div class="product-details">
            <div class="product-principal">
                <img class="product-img-large" src="img/BANNER-4.jpg" alt="">
                <h1>title</h1>
                <h3>price</h3>
                <button>Adicionar ao carrinho</button>
            </div>
            <aside class="aside-images">
                <div class="aside-img"><img src="img/BANNER-4.jpg" alt=""></div>
                <div class="aside-img"><img src="img/BANNER-4.jpg" alt=""></div>
                <div class="aside-img"><img src="img/BANNER-4.jpg" alt=""></div>
            </aside>
        </div>
    </section>

    <section class="description">
        <h1>Descrição</h1>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque voluptates ipsam optio? Temporibus voluptatem modi, minima perspiciatis animi quae incidunt quasi non, iure doloribus quam facilis consectetur repellendus asperiores assumenda.
        </p>
    </section>
</main>