<main>
    <section class="product">
        <h1 class="product-title">Guarda-roupas casal kappesberg</h1>
        <div class="product-details">
            <div class="product-img-large">
                <img src="img/BANNER-4.jpg" alt="">
            </div>
            <aside class="aside-images">
                <div class="aside-img"><img src="img/BANNER-4.jpg" alt=""></div>
                <div class="aside-img"><img src="img/BANNER-4.jpg" alt=""></div>
                <div class="aside-img"><img src="img/BANNER-4.jpg" alt=""></div>
            </aside>
            <div class="product-price">      
                <h2>price</h2>    
                <button>Adicionar ao carrinho</button>
            </div>
        </div>
    </section>

    <section class="description">
        <h1>Descrição</h1>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque voluptates ipsam optio? Temporibus voluptatem modi, minima perspiciatis animi quae incidunt quasi non, iure doloribus quam facilis consectetur repellendus asperiores assumenda.
        </p>
    </section>
</main>