<main>
    <section class="product">
        <h1 class="product-title"><?=$this->view->product['name_product']?></h1>
        <div class="product-details">
            <div class="product-img-large">
                <img src="img/<?=$this->view->product['images']?>" alt="">
            </div>
            <aside class="aside-images">
                <div class="aside-img"><img src="img/<?=$this->view->product['images']?>" alt=""></div>
                <div class="aside-img"><img src="img/<?=$this->view->product['images']?>" alt=""></div>
                <div class="aside-img"><img src="img/<?=$this->view->product['images']?>" alt=""></div>
            </aside>
            <div class="product-price">      
                <h2>R$ <?= number_format($this->view->product['price'], 2) ?></h2>    
                <button onclick="addProductToCar(<?=$this->view->product['id']?>)">Adicionar ao carrinho</button>
            </div>
        </div>
    </section>

    <section class="description">
        <h1>Descrição</h1>
        <p><?=$this->view->product['description']?></p>
    </section>
</main>