<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
</head>
<body>
    <nav class="menu">
        <a class="btn-logo" href="/">Loja</a>
        <ul class="menu-items">
            <li><a class="btn-menu" href="#">Inicio</a></li>
            <li><a class="btn-menu" href="#">Produtos</a></li>
            <li><a class="btn-menu" href="#">Contato</a></li>
            <li><a class="btn-menu" href="#">Sobre</a></li>
            <li>
                <a class="cart" href="#">
                    <i class="fa-solid fa-cart-shopping cart-icon"></i>
                    <span class="cart-number"> <?= $this->view->quantity ?></span>
                    <!-- <span>total: <?= number_format($this->view->total, 2) ?></span> -->
                </a>
            </li>
        </ul>
    </nav>
    
    <?php $this->content(); ?>
</body>
</html>