<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
</head>
<body>
    <nav class="menu">
        <a class="btn-logo" href="/">Loja</a>
        <ul class="menu-items">
            <li><a class="btn-menu" href="/">Inicio</a></li>
            <li><a class="btn-menu" href="/produto">Produtos</a></li>
            <li><a class="btn-menu" href="#">Contato</a></li>
            <li><a class="btn-menu" href="/sobre">Sobre</a></li>
        </ul>
        <div class="menu-hidden-options">
            <a class="cart" href="#">
                <i class="fa-solid fa-cart-shopping cart-icon"></i>
                <span class="cart-number"> 0</span>
                <!-- <span>total: <?= number_format($this->view->total, 2) ?></span> -->
            </a>
            <a class="icon-menu-hidden" onclick="openMenu()" href="#">
                <i class="fa-solid fa-bars"></i>
            </a>
        </div>
    </nav>
    
    <section class="menu-hidden">
        <ul>
            <li><a href="#">Inicio</a></li>
            <li><a href="#">Produtos</a></li>
            <li><a href="#">Contato</a></li>
            <li><a href="#">Sobre</a></li>
        </ul>
    </section>

    <?php $this->content(); ?>

    <footer>
        <small>Desenvolvido por &copy;Tam - 2024</small>
        <div>
            <a class="icon-facebook" href="#"><i class="fa-brands fa-facebook"></i></a>
            <a class="icon-x" href="#"><i class="fa-brands fa-x-twitter"></i></a>
            <a class="icon-youtube" href="#"><i class="fa-brands fa-youtube"></i></a>
        </div>
        <small><strong>contato:</strong> (xx)0 00000000</small> 
    </footer>
    <script src="js/index.js"></script>
</body>
</html>